name: Libmamba Solver Feedback (Experimental Feature)
description: Create a report for the experimental solver
labels:
  - solver::libmamba
  - tag::experimental
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping conda! 🐍

        You are trying out an experimental feature. If you are encountering blocking issues we
        first suggest removing the experimental solver by typing the following code into your
        terminal:

        ```bash
        $ conda remove conda-libmamba-solver
        ```

        Going through bugs and issues takes up a lot of time, so please be so kind and take a few
        minutes to fill out all the areas to the best of your ability.

        There will always be more issues than there is time to do them, and so we will need to
        selectively close issues that don't provide enough information, so we can focus our time
        on helping people like you who fill out the issue form completely. Thank you for your
        collaboration!

        There are also already a lot of open issues, so please take 2 minutes and search through
        existing ones to see if what you are experiencing already exists

        Thanks for helping conda be amazing. We are nothing without people like you helping build
        a better community 💐!
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I searched for other issues and couldn't find a solution or duplication
          required: true
        - label: >-
            I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver)
            and didn't see anything to help
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        And what should have happened instead? This really helps us triage quicker and greatly
        increases the chance that we can get around to solve your issue
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Conda info
      description: |
        Let's get the info on your conda setup. Run the following command from your command line
        and paste the output

        ```bash
        conda info
        ```
      render: Shell
  - type: textarea
    id: config
    attributes:
      label: Conda config
      description: |
        Let's see what your conda config looks like. Run the following command from your command
        line and paste the output

        ```bash
        conda config --show-sources
        ```
      render: Shell
  - type: textarea
    id: list
    attributes:
      label: Conda list
      description: |
        These are the packages installed in your conda environment and the conda channels used.
        They tell us where you are pulling packages from. Make sure you are in the environment
        where you are seeing the issues. Run the following command from your command line and
        paste the output

        ```bash
        conda list --show-channel-urls
        ```
      render: Shell

  - type: textarea
    attributes:
      label: Log file & additional context
      description: |
        Please attach the associated log file (drag and drop the file into the textbox
        below). The logfile path is printed to the command line when running commands with
        the experimental solver enabled.

        Please also include any additional context information or screenshots you think are
        useful here.
